# Site settings
title: Yash&Stuff
description: >
  This is the portfolio site of Yash Dixit.
  I'll be writing about the projects I build, random tech & life. 


author:
  fullname: Yash Dixit
  github: yash-dxt
  twitter: yashhdixit
  # disqus: your_disqus_forum_shortname

plugins:
  - jekyll-analytics

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-123-456          # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

  # Matomo:                   # Add, if you want to track with Matomo (former Piwik Analytics)
  #   url: matomo.example.com # Required - url to Matomo installation without trailing /
  #   siteId: "1234"          # Required - replace with your Matomo site id (Write id as string)

  # Piwik:                    # Add, if you want to track with Piwik
  #   url: piwik.example.com  # Required - url to Piwik installation without trailing /
  #   siteId: "1234"          # Required - replace with your Piwik site id (Write id as string)

  # MPulse:                   # Add if you want to track performance with mPulse
  #   apikey: XXXXX-YYYYY-ZZZZZ-AAAAA-23456   # Required - replace with your mPulse API key

  # Plausible:
  #   domain: 'example.com'   # The domain configured in plausible
  #   source: 'https://plausible.example.com/js/plausible.js' # The source of the javascript

# google_analytics: 'UA-XXXXXXXX-X'

# Syntax highlighting
highlightstyle: ''
styles: [agate, androidstudio, arta, asceti, atelier-cave.dark, atelier-cave.light, atelier-dune.dark, atelier-dune.light, atelier-estuary.dark, atelier-estuary.light, atelier-forest.dark, atelier-forest.light, atelier-heath.dark, atelier-heath.light, atelier-lakeside.dark, atelier-lakeside.light, atelier-plateau.dark, atelier-plateau.light, atelier-savanna.dark, atelier-savanna.light, atelier-seaside.dark, atelier-seaside.light, atelier-sulphurpool.dark, atelier-sulphurpool.light, brown_paper, codepen-embed, color-brewer, dark, darkula, default, docco, far, foundation, github, github-gist, googlecode, grayscale, hopscotch, hybrid, idea, ir_black, kimbie.dark, kimbie.light, magula, mono-blue, monokai, monokai_sublime, obsidian, paraiso.dark, paraiso.light, pojoaque, railscast, rainbow, school_book, solarized_dark, solarized_light, styles_list.txt, sunburst, tomorrow, tomorrow-night-blue, tomorrow-night-bright, tomorrow-night, tomorrow-night-eightie, v, xcode, zenburn]

# Handling Reading
exclude: ["README.md", "README.html"]

# Build settings
highlighter: null
markdown: kramdown
